# ===============================
# 1. BASIC APP CONFIG
# ===============================
spring.application.name=quantity-measurement-app
server.port=8080

# ===============================
# 2. MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=RadheRadhe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# 3. JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# 4. LOGGING CONFIG
# ===============================
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG

# Disable default Spring security password
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ===============================
# 5. JWT CONFIG and OAUTH 
# ===============================

spring.config.import=optional:application-secret.properties

# 7. SWAGGER / OPENAPI
# ===============================
springdoc.swagger-ui.enabled=true

# ===============================
# 8. ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,metrics

# ===============================
# 9. FRONTEND URL
# ===============================
app.frontend.url=http://localhost:5173