#Application Configuration Properties

spring.application.name=Quantity Measurement App
server.port=8080

# MySQL Database (Production)
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=RadheRadhe

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# Fix the Logging (so you can actually see the "Started" message)
logging.level.root=INFO
logging.level.com.app.quantitymeasurement=DEBUG

# Actuator

management.endpoints.web.exposure.include=health, metrics